apiVersion: v1
kind: Pod
metadata:
  name: wca
  namespace: wca
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  terminationGracePeriodSeconds: 0
  nodeSelector:
    own_ip: 100.64.176.33

  containers:

    - name: wca
      image: 100.64.176.12:80/owca:fbcc3e13699b14f448c19a03d5a522f5247ac39c
      env:
        - name: LOG
          value: info
        # Example of providing simple python plugin.
        - name: PEX_INHERIT_PATH
          value: 'true'
        - name: EXTRA_COMPONENT
          value: example_allocator:ExampleAllocator
        - name: PYTHONPATH
          value: /
        - name: EXTRA_OPTIONS
          value: '--log example_allocator:debug'
      volumeMounts:
        - name: kubeletcert
          mountPath: /etc/kubernetes/ssl/
        - name: wca-config
          mountPath: /etc/wca/
        - name: var-lib-wca
          mountPath: /var/lib/wca
        - name: cgroup
          mountPath: /sys/fs/cgroup/
        - name: resctrl
          mountPath: /sys/fs/resctrl/

        # Allocator plugin can be simple python module.
        - name: wca-allocator-plugin
          mountPath: /example_allocator.py
          subPath: example_allocator.py

    - name: node-exporter
      image: prom/node-exporter@sha256:ffc3e0adf58771cb2097aa0b074a6fe68b4925ba75c2e1c41f41ae656eebee11
      securityContext:
        privileged: true
      args:
        - --collector.procfs
        - /host/proc
        - --collector.sysfs
        - /host/sys
        - --collector.filesystem.ignored-mount-points
        - '"^/(sys|proc|dev|host|etc)($|/)"'
        - --collector.textfile.directory
        - /var/lib/wca

      volumeMounts:
        - name: var-lib-wca
          mountPath: /var/lib/wca
        - name: dev
          mountPath: /host/dev
        - name: proc
          mountPath: /host/proc
        - name: sys
          mountPath: /host/sys
        - name: rootfs
          mountPath: /rootfs

  volumes:
    #### workload-collocation-agent
    - name: wca-config
      configMap:
        name: wca-config
    - name: wca-allocator-plugin
      configMap:
        name: wca-allocator-plugin
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup/
    - name: resctrl
      hostPath:
        path: /sys/fs/resctrl/
    - name: kubeletcert
      hostPath:
        path: /etc/kubernetes/ssl/
    #### common
    - name: var-lib-wca
      emptyDir: {}
    #### node_exporter
    - name: proc
      hostPath:
        path: /proc
    - name: dev
      hostPath:
        path: /dev
    - name: sys
      hostPath:
        path: /sys
    - name: rootfs
      hostPath:
        path: /
