apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    kubernetes.io/cluster-service: "true"
    k8s-app: Grafana
    kubernetes.io/name: grafana
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 32135
    port: 3000
    protocol: TCP
  selector:
    name: grafana
