nameSuffix: -small

bases:
- ../base

commonLabels:
  app: redis-small
  size: small

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=30
    - threads=4
    - keymaximum=200000   # 200k
    - datasize=1024       # 220-250M

patchesStrategicMerge:
  - resources.yaml
