[general]
threads = 4
connections = 20
windows = 3600
duration = 1
request-timeout = 200
connect-timeout = 500

[[workload]]
name = "get"
method = "get"
rate = 30_000
period = 15
amplitude = 2000
  [[workload.parameter]]
  style = "random"
  size = 4
  regenerate = true

[[workload]]
name = "set"
method = "set"
rate = 15_000
period = 15
amplitude = 2000
  [[workload.parameter]]
  style = "random"
  size = 4
  regenerate = true
  [[workload.parameter]]
  style = "random"
  size = 128
  regenerate = false

