nameSuffix: -big
bases:
- ../base

commonLabels:
  app: memcached-big
  size: big

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=40000    # 40kB * 1M  <= 50GB
  - qps=20000      # 2M

patchesStrategicMerge:
  - resources.yaml
