nameSuffix: -stream-small
bases:
- ../base

commonLabels:
  app: stress-stream-small
  size: small

configMapGenerator:
- name: stress
  behavior: merge
  literals:
    - extra='--stream 1 --stream-l3-size=512m --stream-index=0' # 6GB RSS

patchesStrategicMerge:
  - resources.yaml
