apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stress
spec:
  template:
    spec:
      containers:
        - name: stress
          resources:
            requests:
              cpu: 1
              memory: 4G
