nameSuffix: -small
bases:
- ../base

commonLabels:
  app: memcached-small
  size: small

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=800       # 0.8kB * 1M <= 1GB
  - qps=50000       # 200k per second

patchesStrategicMerge:
  - resources.yaml
