apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 2
              memory: 2G # valueSize*records = 10k * 1M = 2G
