nameSuffix: -medium

bases:
- ../base

commonLabels:
  app: redis-medium
  size: medium

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=50
    - threads=5
    - keymaximum=5000000   # 5M
    - datasize=1024        # 5.5-6GB

patchesStrategicMerge:
  - resources.yaml
