apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 2
              memory: 12G # valueSize*records = 10k * 1M = 10G
