nameSuffix: -medium
bases:
- ../base

commonLabels:
  app: memcached-medium
  size: medium

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=8000     # 8kB * 1M <= 10G
  - qps=40000      # 500k

patchesStrategicMerge:
  - resources.yaml
